"""add_client_lookup_tables

Revision ID: 74f8d51409bc
Revises: abad039e13a9
Create Date: 2025-12-18 13:07:45.136108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f8d51409bc'
down_revision: Union[str, Sequence[str], None] = 'abad039e13a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookup_classificazioni_cliente',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_classificazioni_cliente_attivo'), 'lookup_classificazioni_cliente', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_classificazioni_cliente_codice'), 'lookup_classificazioni_cliente', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_classificazioni_cliente_id'), 'lookup_classificazioni_cliente', ['id'], unique=False)
    op.create_table('lookup_stati_cliente',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_stati_cliente_attivo'), 'lookup_stati_cliente', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_stati_cliente_codice'), 'lookup_stati_cliente', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_stati_cliente_id'), 'lookup_stati_cliente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lookup_stati_cliente_id'), table_name='lookup_stati_cliente')
    op.drop_index(op.f('ix_lookup_stati_cliente_codice'), table_name='lookup_stati_cliente')
    op.drop_index(op.f('ix_lookup_stati_cliente_attivo'), table_name='lookup_stati_cliente')
    op.drop_table('lookup_stati_cliente')
    op.drop_index(op.f('ix_lookup_classificazioni_cliente_id'), table_name='lookup_classificazioni_cliente')
    op.drop_index(op.f('ix_lookup_classificazioni_cliente_codice'), table_name='lookup_classificazioni_cliente')
    op.drop_index(op.f('ix_lookup_classificazioni_cliente_attivo'), table_name='lookup_classificazioni_cliente')
    op.drop_table('lookup_classificazioni_cliente')
    # ### end Alembic commands ###
