"""add tecnici extra fields

Revision ID: 95dc2616b1cf
Revises: fa0df4950c09
Create Date: 2025-12-18 12:36:35.872145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dc2616b1cf'
down_revision: Union[str, Sequence[str], None] = 'fa0df4950c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_calendario_eventi_richiesta', 'calendario_eventi', 'richieste_intervento', ['richiesta_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_calendario_eventi_intervento', 'calendario_eventi', 'interventi', ['intervento_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_intervento_calendario', 'interventi', 'calendario_eventi', ['evento_calendario_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_intervento_richiesta', 'interventi', 'richieste_intervento', ['richiesta_id'], ['id'], use_alter=True)
    op.add_column('tecnici', sa.Column('cellulare', sa.String(length=50), nullable=True))
    op.add_column('tecnici', sa.Column('interno_telefonico', sa.String(length=20), nullable=True))
    op.add_column('tecnici', sa.Column('telegram_id', sa.String(length=100), nullable=True))
    op.add_column('tecnici', sa.Column('codice_tecnico', sa.String(length=50), nullable=True))
    op.add_column('tecnici', sa.Column('username_ad', sa.String(length=100), nullable=True))
    op.add_column('tecnici', sa.Column('note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tecnici_codice_tecnico'), 'tecnici', ['codice_tecnico'], unique=False)
    op.create_index(op.f('ix_tecnici_username_ad'), 'tecnici', ['username_ad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tecnici_username_ad'), table_name='tecnici')
    op.drop_index(op.f('ix_tecnici_codice_tecnico'), table_name='tecnici')
    op.drop_column('tecnici', 'note')
    op.drop_column('tecnici', 'username_ad')
    op.drop_column('tecnici', 'codice_tecnico')
    op.drop_column('tecnici', 'telegram_id')
    op.drop_column('tecnici', 'interno_telefonico')
    op.drop_column('tecnici', 'cellulare')
    op.drop_constraint('fk_intervento_richiesta', 'interventi', type_='foreignkey')
    op.drop_constraint('fk_intervento_calendario', 'interventi', type_='foreignkey')
    op.drop_constraint('fk_calendario_eventi_intervento', 'calendario_eventi', type_='foreignkey')
    op.drop_constraint('fk_calendario_eventi_richiesta', 'calendario_eventi', type_='foreignkey')
    # ### end Alembic commands ###
