"""extend_client_tables

Revision ID: abad039e13a9
Revises: 95dc2616b1cf
Create Date: 2025-12-18 13:06:25.741755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abad039e13a9'
down_revision: Union[str, Sequence[str], None] = '95dc2616b1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sedi_cliente',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome_sede', sa.String(length=100), nullable=False),
    sa.Column('codice_sede', sa.String(length=50), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=False),
    sa.Column('cap', sa.String(length=10), nullable=True),
    sa.Column('citta', sa.String(length=100), nullable=False),
    sa.Column('provincia', sa.String(length=2), nullable=True),
    sa.Column('nazione', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('orari_servizio', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sedi_cliente_attivo'), 'sedi_cliente', ['attivo'], unique=False)
    op.create_index(op.f('ix_sedi_cliente_cliente_id'), 'sedi_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_sedi_cliente_id'), 'sedi_cliente', ['id'], unique=False)
    op.add_column('cache_clienti', sa.Column('stato_cliente', sa.String(length=20), nullable=True))
    op.add_column('cache_clienti', sa.Column('classificazione', sa.String(length=50), nullable=True))
    op.add_column('cache_clienti', sa.Column('referente_it_id', sa.Integer(), nullable=True))
    op.add_column('cache_clienti', sa.Column('orari_servizio', sa.Text(), nullable=True))
    op.add_column('cache_clienti', sa.Column('nomi_alternativi', sa.Text(), nullable=True))
    op.create_index(op.f('ix_cache_clienti_stato_cliente'), 'cache_clienti', ['stato_cliente'], unique=False)
    op.create_foreign_key('fk_cache_clienti_referente_it', 'cache_clienti', 'cache_referenti', ['referente_it_id'], ['id'], use_alter=True)
    op.add_column('cache_referenti', sa.Column('sede_id', sa.Integer(), nullable=True))
    op.add_column('cache_referenti', sa.Column('interno_telefonico', sa.String(length=20), nullable=True))
    op.add_column('cache_referenti', sa.Column('referente_it', sa.Integer(), nullable=True))
    op.add_column('cache_referenti', sa.Column('note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_cache_referenti_cognome'), 'cache_referenti', ['cognome'], unique=False)
    op.create_index(op.f('ix_cache_referenti_email'), 'cache_referenti', ['email'], unique=False)
    op.create_index(op.f('ix_cache_referenti_nome'), 'cache_referenti', ['nome'], unique=False)
    op.create_foreign_key(None, 'cache_referenti', 'sedi_cliente', ['sede_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cache_referenti', type_='foreignkey')
    op.drop_index(op.f('ix_cache_referenti_nome'), table_name='cache_referenti')
    op.drop_index(op.f('ix_cache_referenti_email'), table_name='cache_referenti')
    op.drop_index(op.f('ix_cache_referenti_cognome'), table_name='cache_referenti')
    op.drop_column('cache_referenti', 'note')
    op.drop_column('cache_referenti', 'referente_it')
    op.drop_column('cache_referenti', 'interno_telefonico')
    op.drop_column('cache_referenti', 'sede_id')
    op.drop_constraint('fk_cache_clienti_referente_it', 'cache_clienti', type_='foreignkey')
    op.drop_index(op.f('ix_cache_clienti_stato_cliente'), table_name='cache_clienti')
    op.drop_column('cache_clienti', 'nomi_alternativi')
    op.drop_column('cache_clienti', 'orari_servizio')
    op.drop_column('cache_clienti', 'referente_it_id')
    op.drop_column('cache_clienti', 'classificazione')
    op.drop_column('cache_clienti', 'stato_cliente')
    op.drop_index(op.f('ix_sedi_cliente_id'), table_name='sedi_cliente')
    op.drop_index(op.f('ix_sedi_cliente_cliente_id'), table_name='sedi_cliente')
    op.drop_index(op.f('ix_sedi_cliente_attivo'), table_name='sedi_cliente')
    op.drop_table('sedi_cliente')
    # ### end Alembic commands ###
