"""Initial migration with all models

Revision ID: fa0df4950c09
Revises: 
Create Date: 2025-12-17 21:50:30.532148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0df4950c09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_clienti',
    sa.Column('codice_gestionale', sa.String(length=50), nullable=False),
    sa.Column('ragione_sociale', sa.String(length=255), nullable=False),
    sa.Column('partita_iva', sa.String(length=20), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=20), nullable=True),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.Column('cap', sa.String(length=10), nullable=True),
    sa.Column('citta', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=2), nullable=True),
    sa.Column('nazione', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('pec', sa.String(length=255), nullable=True),
    sa.Column('sito_web', sa.String(length=255), nullable=True),
    sa.Column('ultimo_sync', sa.DateTime(), nullable=False),
    sa.Column('hash_dati', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_clienti_attivo'), 'cache_clienti', ['attivo'], unique=False)
    op.create_index(op.f('ix_cache_clienti_codice_gestionale'), 'cache_clienti', ['codice_gestionale'], unique=True)
    op.create_index(op.f('ix_cache_clienti_id'), 'cache_clienti', ['id'], unique=False)
    op.create_index(op.f('ix_cache_clienti_ragione_sociale'), 'cache_clienti', ['ragione_sociale'], unique=False)
    op.create_table('kb_categorie',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('icona', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('pubblica', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['kb_categorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_categorie_attivo'), 'kb_categorie', ['attivo'], unique=False)
    op.create_index(op.f('ix_kb_categorie_id'), 'kb_categorie', ['id'], unique=False)
    op.create_index(op.f('ix_kb_categorie_parent_id'), 'kb_categorie', ['parent_id'], unique=False)
    op.create_table('kb_tags',
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_tags_attivo'), 'kb_tags', ['attivo'], unique=False)
    op.create_index(op.f('ix_kb_tags_id'), 'kb_tags', ['id'], unique=False)
    op.create_index(op.f('ix_kb_tags_nome'), 'kb_tags', ['nome'], unique=True)
    op.create_index(op.f('ix_kb_tags_slug'), 'kb_tags', ['slug'], unique=True)
    op.create_table('lookup_canali_richiesta',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_canali_richiesta_attivo'), 'lookup_canali_richiesta', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_canali_richiesta_codice'), 'lookup_canali_richiesta', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_canali_richiesta_id'), 'lookup_canali_richiesta', ['id'], unique=False)
    op.create_table('lookup_categorie_attivita',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('prezzo_unitario_default', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_categorie_attivita_attivo'), 'lookup_categorie_attivita', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_categorie_attivita_codice'), 'lookup_categorie_attivita', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_categorie_attivita_id'), 'lookup_categorie_attivita', ['id'], unique=False)
    op.create_table('lookup_origini_intervento',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_origini_intervento_attivo'), 'lookup_origini_intervento', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_origini_intervento_codice'), 'lookup_origini_intervento', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_origini_intervento_id'), 'lookup_origini_intervento', ['id'], unique=False)
    op.create_table('lookup_priorita',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('livello', sa.Integer(), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_priorita_attivo'), 'lookup_priorita', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_priorita_codice'), 'lookup_priorita', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_priorita_id'), 'lookup_priorita', ['id'], unique=False)
    op.create_table('lookup_reparti',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_reparti_attivo'), 'lookup_reparti', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_reparti_codice'), 'lookup_reparti', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_reparti_id'), 'lookup_reparti', ['id'], unique=False)
    op.create_table('lookup_ruoli_utente',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('permessi', sa.String(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_ruoli_utente_attivo'), 'lookup_ruoli_utente', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_ruoli_utente_codice'), 'lookup_ruoli_utente', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_ruoli_utente_id'), 'lookup_ruoli_utente', ['id'], unique=False)
    op.create_table('lookup_stati_intervento',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('finale', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_stati_intervento_attivo'), 'lookup_stati_intervento', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_stati_intervento_codice'), 'lookup_stati_intervento', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_stati_intervento_id'), 'lookup_stati_intervento', ['id'], unique=False)
    op.create_table('lookup_stati_ticket',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('finale', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_stati_ticket_attivo'), 'lookup_stati_ticket', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_stati_ticket_codice'), 'lookup_stati_ticket', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_stati_ticket_id'), 'lookup_stati_ticket', ['id'], unique=False)
    op.create_table('lookup_tipi_intervento',
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=200), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('richiede_viaggio', sa.Integer(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_tipi_intervento_attivo'), 'lookup_tipi_intervento', ['attivo'], unique=False)
    op.create_index(op.f('ix_lookup_tipi_intervento_codice'), 'lookup_tipi_intervento', ['codice'], unique=True)
    op.create_index(op.f('ix_lookup_tipi_intervento_id'), 'lookup_tipi_intervento', ['id'], unique=False)
    op.create_table('sla_definizioni',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('tempo_risposta_critica', sa.Integer(), nullable=True),
    sa.Column('tempo_risposta_urgente', sa.Integer(), nullable=True),
    sa.Column('tempo_risposta_alta', sa.Integer(), nullable=True),
    sa.Column('tempo_risposta_normale', sa.Integer(), nullable=True),
    sa.Column('tempo_risposta_bassa', sa.Integer(), nullable=True),
    sa.Column('tempo_risoluzione_critica', sa.Integer(), nullable=True),
    sa.Column('tempo_risoluzione_urgente', sa.Integer(), nullable=True),
    sa.Column('tempo_risoluzione_alta', sa.Integer(), nullable=True),
    sa.Column('tempo_risoluzione_normale', sa.Integer(), nullable=True),
    sa.Column('tempo_risoluzione_bassa', sa.Integer(), nullable=True),
    sa.Column('ora_inizio_lavorativa', sa.String(length=5), nullable=True),
    sa.Column('ora_fine_lavorativa', sa.String(length=5), nullable=True),
    sa.Column('giorni_lavorativi', sa.String(length=50), nullable=True),
    sa.Column('include_festivi', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_sla_definizioni_attivo'), 'sla_definizioni', ['attivo'], unique=False)
    op.create_index(op.f('ix_sla_definizioni_id'), 'sla_definizioni', ['id'], unique=False)
    op.create_table('sync_log',
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('direzione', sa.String(length=20), nullable=False),
    sa.Column('records_processati', sa.Integer(), nullable=True),
    sa.Column('records_inseriti', sa.Integer(), nullable=True),
    sa.Column('records_aggiornati', sa.Integer(), nullable=True),
    sa.Column('records_errori', sa.Integer(), nullable=True),
    sa.Column('inizio', sa.DateTime(), nullable=False),
    sa.Column('fine', sa.DateTime(), nullable=True),
    sa.Column('durata_secondi', sa.Integer(), nullable=True),
    sa.Column('successo', sa.Integer(), nullable=True),
    sa.Column('errore', sa.Text(), nullable=True),
    sa.Column('dettagli_errori', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_attivo'), 'sync_log', ['attivo'], unique=False)
    op.create_index(op.f('ix_sync_log_id'), 'sync_log', ['id'], unique=False)
    op.create_index(op.f('ix_sync_log_tipo'), 'sync_log', ['tipo'], unique=False)
    op.create_table('cache_contratti',
    sa.Column('codice_gestionale', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=False),
    sa.Column('tipo_contratto', sa.String(length=100), nullable=True),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('attivo_gestionale', sa.Integer(), nullable=True),
    sa.Column('ore_incluse', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ore_utilizzate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('importo_annuo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sla_id', sa.Integer(), nullable=True),
    sa.Column('ultimo_sync', sa.DateTime(), nullable=False),
    sa.Column('hash_dati', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.ForeignKeyConstraint(['sla_id'], ['sla_definizioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_contratti_attivo'), 'cache_contratti', ['attivo'], unique=False)
    op.create_index(op.f('ix_cache_contratti_cliente_id'), 'cache_contratti', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cache_contratti_codice_gestionale'), 'cache_contratti', ['codice_gestionale'], unique=True)
    op.create_index(op.f('ix_cache_contratti_id'), 'cache_contratti', ['id'], unique=False)
    op.create_table('cache_referenti',
    sa.Column('codice_gestionale', sa.String(length=50), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('ruolo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('cellulare', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contatto_principale', sa.Integer(), nullable=True),
    sa.Column('riceve_notifiche', sa.Integer(), nullable=True),
    sa.Column('ultimo_sync', sa.DateTime(), nullable=False),
    sa.Column('hash_dati', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_referenti_attivo'), 'cache_referenti', ['attivo'], unique=False)
    op.create_index(op.f('ix_cache_referenti_cliente_id'), 'cache_referenti', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cache_referenti_codice_gestionale'), 'cache_referenti', ['codice_gestionale'], unique=True)
    op.create_index(op.f('ix_cache_referenti_id'), 'cache_referenti', ['id'], unique=False)
    op.create_table('clienti_portale',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('visualizza_tutti_ticket_azienda', sa.Integer(), nullable=True),
    sa.Column('puo_aprire_ticket', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Integer(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clienti_portale_attivo'), 'clienti_portale', ['attivo'], unique=False)
    op.create_index(op.f('ix_clienti_portale_email'), 'clienti_portale', ['email'], unique=True)
    op.create_index(op.f('ix_clienti_portale_id'), 'clienti_portale', ['id'], unique=False)
    op.create_table('tecnici',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('reparto_id', sa.Integer(), nullable=True),
    sa.Column('ruolo_id', sa.Integer(), nullable=False),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True),
    sa.Column('ldap_enabled', sa.Integer(), nullable=True),
    sa.Column('colore_calendario', sa.String(length=7), nullable=True),
    sa.Column('notifiche_email', sa.Integer(), nullable=True),
    sa.Column('notifiche_push', sa.Integer(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reparto_id'], ['lookup_reparti.id'], ),
    sa.ForeignKeyConstraint(['ruolo_id'], ['lookup_ruoli_utente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnici_attivo'), 'tecnici', ['attivo'], unique=False)
    op.create_index(op.f('ix_tecnici_email'), 'tecnici', ['email'], unique=True)
    op.create_index(op.f('ix_tecnici_id'), 'tecnici', ['id'], unique=False)
    op.create_index(op.f('ix_tecnici_username'), 'tecnici', ['username'], unique=True)
    op.create_table('asset',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('indirizzo_ip', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('sistema_operativo', sa.String(length=200), nullable=True),
    sa.Column('versione_os', sa.String(length=100), nullable=True),
    sa.Column('specifiche_hardware', sa.Text(), nullable=True),
    sa.Column('licenze_software', sa.Text(), nullable=True),
    sa.Column('stato', sa.String(length=50), nullable=True),
    sa.Column('ubicazione_fisica', sa.String(length=255), nullable=True),
    sa.Column('contratto_id', sa.Integer(), nullable=True),
    sa.Column('garanzia_scadenza', sa.DateTime(), nullable=True),
    sa.Column('fornitore', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.ForeignKeyConstraint(['contratto_id'], ['cache_contratti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_attivo'), 'asset', ['attivo'], unique=False)
    op.create_index(op.f('ix_asset_cliente_id'), 'asset', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_index(op.f('ix_asset_tipo'), 'asset', ['tipo'], unique=False)
    op.create_table('calendario_eventi',
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('luogo', sa.String(length=255), nullable=True),
    sa.Column('data_inizio', sa.DateTime(), nullable=False),
    sa.Column('data_fine', sa.DateTime(), nullable=False),
    sa.Column('tipo_intervento_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('richiesta_id', sa.Integer(), nullable=True),
    sa.Column('intervento_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_principale_id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=50), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('outlook_event_id', sa.String(length=255), nullable=True),
    sa.Column('caldav_uid', sa.String(length=255), nullable=True),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('promemoria_minuti', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.ForeignKeyConstraint(['intervento_id'], ['interventi.id'], name='fk_calendario_eventi_intervento', use_alter=True),
    sa.ForeignKeyConstraint(['richiesta_id'], ['richieste_intervento.id'], name='fk_calendario_eventi_richiesta', use_alter=True),
    sa.ForeignKeyConstraint(['tecnico_principale_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['tipo_intervento_id'], ['lookup_tipi_intervento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendario_eventi_attivo'), 'calendario_eventi', ['attivo'], unique=False)
    op.create_index(op.f('ix_calendario_eventi_cliente_id'), 'calendario_eventi', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_calendario_eventi_data_inizio'), 'calendario_eventi', ['data_inizio'], unique=False)
    op.create_index(op.f('ix_calendario_eventi_id'), 'calendario_eventi', ['id'], unique=False)
    op.create_index(op.f('ix_calendario_eventi_tecnico_principale_id'), 'calendario_eventi', ['tecnico_principale_id'], unique=False)
    op.create_table('calendario_sync_log',
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('direzione', sa.String(length=20), nullable=True),
    sa.Column('eventi_sincronizzati', sa.Integer(), nullable=True),
    sa.Column('eventi_errori', sa.Integer(), nullable=True),
    sa.Column('errore', sa.Text(), nullable=True),
    sa.Column('dettagli', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendario_sync_log_attivo'), 'calendario_sync_log', ['attivo'], unique=False)
    op.create_index(op.f('ix_calendario_sync_log_id'), 'calendario_sync_log', ['id'], unique=False)
    op.create_index(op.f('ix_calendario_sync_log_tecnico_id'), 'calendario_sync_log', ['tecnico_id'], unique=False)
    op.create_table('kb_articoli',
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('contenuto', sa.Text(), nullable=False),
    sa.Column('formato', sa.String(length=20), nullable=True),
    sa.Column('autore_id', sa.Integer(), nullable=False),
    sa.Column('pubblicato', sa.Integer(), nullable=True),
    sa.Column('pubblico', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('visualizzazioni', sa.Integer(), nullable=True),
    sa.Column('utile_count', sa.Integer(), nullable=True),
    sa.Column('non_utile_count', sa.Integer(), nullable=True),
    sa.Column('versione', sa.Integer(), nullable=True),
    sa.Column('parent_versione_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['autore_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['kb_categorie.id'], ),
    sa.ForeignKeyConstraint(['parent_versione_id'], ['kb_articoli.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_articoli_attivo'), 'kb_articoli', ['attivo'], unique=False)
    op.create_index(op.f('ix_kb_articoli_categoria_id'), 'kb_articoli', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_kb_articoli_id'), 'kb_articoli', ['id'], unique=False)
    op.create_index(op.f('ix_kb_articoli_slug'), 'kb_articoli', ['slug'], unique=True)
    op.create_index(op.f('ix_kb_articoli_titolo'), 'kb_articoli', ['titolo'], unique=False)
    op.create_table('asset_credenziali',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descrizione', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('note_encrypted', sa.Text(), nullable=True),
    sa.Column('scadenza', sa.DateTime(), nullable=True),
    sa.Column('ultima_rotazione', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_credenziali_asset_id'), 'asset_credenziali', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_credenziali_attivo'), 'asset_credenziali', ['attivo'], unique=False)
    op.create_index(op.f('ix_asset_credenziali_id'), 'asset_credenziali', ['id'], unique=False)
    op.create_table('calendario_tecnici',
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('ruolo', sa.String(length=50), nullable=True),
    sa.Column('confermato', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['calendario_eventi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendario_tecnici_attivo'), 'calendario_tecnici', ['attivo'], unique=False)
    op.create_index(op.f('ix_calendario_tecnici_evento_id'), 'calendario_tecnici', ['evento_id'], unique=False)
    op.create_index(op.f('ix_calendario_tecnici_id'), 'calendario_tecnici', ['id'], unique=False)
    op.create_index(op.f('ix_calendario_tecnici_tecnico_id'), 'calendario_tecnici', ['tecnico_id'], unique=False)
    op.create_table('kb_articoli_feedback',
    sa.Column('articolo_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('utile', sa.Integer(), nullable=False),
    sa.Column('commento', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['articolo_id'], ['kb_articoli.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_articoli_feedback_articolo_id'), 'kb_articoli_feedback', ['articolo_id'], unique=False)
    op.create_index(op.f('ix_kb_articoli_feedback_attivo'), 'kb_articoli_feedback', ['attivo'], unique=False)
    op.create_index(op.f('ix_kb_articoli_feedback_id'), 'kb_articoli_feedback', ['id'], unique=False)
    op.create_table('kb_articoli_tags',
    sa.Column('articolo_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['articolo_id'], ['kb_articoli.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['kb_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_articoli_tags_articolo_id'), 'kb_articoli_tags', ['articolo_id'], unique=False)
    op.create_index(op.f('ix_kb_articoli_tags_attivo'), 'kb_articoli_tags', ['attivo'], unique=False)
    op.create_index(op.f('ix_kb_articoli_tags_id'), 'kb_articoli_tags', ['id'], unique=False)
    op.create_index(op.f('ix_kb_articoli_tags_tag_id'), 'kb_articoli_tags', ['tag_id'], unique=False)
    op.create_table('ticket',
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('referente_id', sa.Integer(), nullable=True),
    sa.Column('referente_nome', sa.String(length=200), nullable=True),
    sa.Column('canale_id', sa.Integer(), nullable=False),
    sa.Column('priorita_id', sa.Integer(), nullable=False),
    sa.Column('stato_id', sa.Integer(), nullable=False),
    sa.Column('oggetto', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('tecnico_assegnato_id', sa.Integer(), nullable=True),
    sa.Column('reparto_id', sa.Integer(), nullable=True),
    sa.Column('contratto_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('sla_scadenza_risposta', sa.DateTime(), nullable=True),
    sa.Column('sla_scadenza_risoluzione', sa.DateTime(), nullable=True),
    sa.Column('sla_prima_risposta_at', sa.DateTime(), nullable=True),
    sa.Column('sla_paused_at', sa.DateTime(), nullable=True),
    sa.Column('sla_paused_total_minutes', sa.Integer(), nullable=True),
    sa.Column('data_chiusura', sa.DateTime(), nullable=True),
    sa.Column('tipo_chiusura', sa.String(length=50), nullable=True),
    sa.Column('note_chiusura', sa.Text(), nullable=True),
    sa.Column('chiuso_da_id', sa.Integer(), nullable=True),
    sa.Column('kb_articolo_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['canale_id'], ['lookup_canali_richiesta.id'], ),
    sa.ForeignKeyConstraint(['chiuso_da_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.ForeignKeyConstraint(['contratto_id'], ['cache_contratti.id'], ),
    sa.ForeignKeyConstraint(['kb_articolo_id'], ['kb_articoli.id'], ),
    sa.ForeignKeyConstraint(['priorita_id'], ['lookup_priorita.id'], ),
    sa.ForeignKeyConstraint(['referente_id'], ['cache_referenti.id'], ),
    sa.ForeignKeyConstraint(['reparto_id'], ['lookup_reparti.id'], ),
    sa.ForeignKeyConstraint(['stato_id'], ['lookup_stati_ticket.id'], ),
    sa.ForeignKeyConstraint(['tecnico_assegnato_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_attivo'), 'ticket', ['attivo'], unique=False)
    op.create_index(op.f('ix_ticket_cliente_id'), 'ticket', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_numero'), 'ticket', ['numero'], unique=True)
    op.create_index(op.f('ix_ticket_stato_id'), 'ticket', ['stato_id'], unique=False)
    op.create_index(op.f('ix_ticket_tecnico_assegnato_id'), 'ticket', ['tecnico_assegnato_id'], unique=False)
    op.create_table('asset_credenziali_accessi',
    sa.Column('credenziale_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['credenziale_id'], ['asset_credenziali.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_credenziali_accessi_attivo'), 'asset_credenziali_accessi', ['attivo'], unique=False)
    op.create_index(op.f('ix_asset_credenziali_accessi_credenziale_id'), 'asset_credenziali_accessi', ['credenziale_id'], unique=False)
    op.create_index(op.f('ix_asset_credenziali_accessi_id'), 'asset_credenziali_accessi', ['id'], unique=False)
    op.create_table('interventi',
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('serie', sa.String(length=20), nullable=True),
    sa.Column('origine_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('richiesta_id', sa.Integer(), nullable=True),
    sa.Column('evento_calendario_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('contratto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_intervento_id', sa.Integer(), nullable=False),
    sa.Column('stato_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('oggetto', sa.String(length=200), nullable=False),
    sa.Column('descrizione_lavoro', sa.Text(), nullable=True),
    sa.Column('note_interne', sa.Text(), nullable=True),
    sa.Column('data_inizio', sa.DateTime(), nullable=True),
    sa.Column('data_fine', sa.DateTime(), nullable=True),
    sa.Column('firma_cliente', sa.Text(), nullable=True),
    sa.Column('firma_nome', sa.String(length=200), nullable=True),
    sa.Column('firma_ruolo', sa.String(length=100), nullable=True),
    sa.Column('firma_data', sa.DateTime(), nullable=True),
    sa.Column('sincronizzato_gestionale', sa.Integer(), nullable=True),
    sa.Column('codice_gestionale', sa.String(length=50), nullable=True),
    sa.Column('data_sincronizzazione', sa.DateTime(), nullable=True),
    sa.Column('errore_sincronizzazione', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.ForeignKeyConstraint(['contratto_id'], ['cache_contratti.id'], ),
    sa.ForeignKeyConstraint(['evento_calendario_id'], ['calendario_eventi.id'], name='fk_intervento_calendario', use_alter=True),
    sa.ForeignKeyConstraint(['origine_id'], ['lookup_origini_intervento.id'], ),
    sa.ForeignKeyConstraint(['richiesta_id'], ['richieste_intervento.id'], name='fk_intervento_richiesta', use_alter=True),
    sa.ForeignKeyConstraint(['stato_id'], ['lookup_stati_intervento.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['tipo_intervento_id'], ['lookup_tipi_intervento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventi_attivo'), 'interventi', ['attivo'], unique=False)
    op.create_index(op.f('ix_interventi_cliente_id'), 'interventi', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_interventi_id'), 'interventi', ['id'], unique=False)
    op.create_index(op.f('ix_interventi_numero'), 'interventi', ['numero'], unique=True)
    op.create_index(op.f('ix_interventi_sincronizzato_gestionale'), 'interventi', ['sincronizzato_gestionale'], unique=False)
    op.create_index(op.f('ix_interventi_stato_id'), 'interventi', ['stato_id'], unique=False)
    op.create_index(op.f('ix_interventi_tecnico_id'), 'interventi', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_interventi_ticket_id'), 'interventi', ['ticket_id'], unique=False)
    op.create_table('richieste_intervento',
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('oggetto', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('priorita_id', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=50), nullable=True),
    sa.Column('data_richiesta', sa.DateTime(), nullable=False),
    sa.Column('data_preferita', sa.DateTime(), nullable=True),
    sa.Column('tecnico_richiesto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_intervento_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cache_clienti.id'], ),
    sa.ForeignKeyConstraint(['priorita_id'], ['lookup_priorita.id'], ),
    sa.ForeignKeyConstraint(['tecnico_richiesto_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['tipo_intervento_id'], ['lookup_tipi_intervento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_richieste_intervento_attivo'), 'richieste_intervento', ['attivo'], unique=False)
    op.create_index(op.f('ix_richieste_intervento_cliente_id'), 'richieste_intervento', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_richieste_intervento_id'), 'richieste_intervento', ['id'], unique=False)
    op.create_index(op.f('ix_richieste_intervento_stato'), 'richieste_intervento', ['stato'], unique=False)
    op.create_index(op.f('ix_richieste_intervento_ticket_id'), 'richieste_intervento', ['ticket_id'], unique=False)
    op.create_table('ticket_allegati',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('nome_file', sa.String(length=255), nullable=False),
    sa.Column('nome_originale', sa.String(length=255), nullable=False),
    sa.Column('percorso', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('dimensione', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_allegati_attivo'), 'ticket_allegati', ['attivo'], unique=False)
    op.create_index(op.f('ix_ticket_allegati_id'), 'ticket_allegati', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_allegati_ticket_id'), 'ticket_allegati', ['ticket_id'], unique=False)
    op.create_table('ticket_messaggi',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('mittente_tipo', sa.String(length=20), nullable=False),
    sa.Column('mittente_tecnico_id', sa.Integer(), nullable=True),
    sa.Column('mittente_cliente_id', sa.Integer(), nullable=True),
    sa.Column('mittente_nome', sa.String(length=200), nullable=True),
    sa.Column('messaggio', sa.Text(), nullable=False),
    sa.Column('letto', sa.Integer(), nullable=True),
    sa.Column('letto_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mittente_cliente_id'], ['clienti_portale.id'], ),
    sa.ForeignKeyConstraint(['mittente_tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messaggi_attivo'), 'ticket_messaggi', ['attivo'], unique=False)
    op.create_index(op.f('ix_ticket_messaggi_id'), 'ticket_messaggi', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_messaggi_ticket_id'), 'ticket_messaggi', ['ticket_id'], unique=False)
    op.create_table('ticket_note',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_note_attivo'), 'ticket_note', ['attivo'], unique=False)
    op.create_index(op.f('ix_ticket_note_id'), 'ticket_note', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_note_ticket_id'), 'ticket_note', ['ticket_id'], unique=False)
    op.create_table('ticket_storico',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('azione', sa.String(length=100), nullable=False),
    sa.Column('campo_modificato', sa.String(length=100), nullable=True),
    sa.Column('valore_precedente', sa.Text(), nullable=True),
    sa.Column('valore_nuovo', sa.Text(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_storico_attivo'), 'ticket_storico', ['attivo'], unique=False)
    op.create_index(op.f('ix_ticket_storico_id'), 'ticket_storico', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_storico_ticket_id'), 'ticket_storico', ['ticket_id'], unique=False)
    op.create_table('asset_storico',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('intervento_id', sa.Integer(), nullable=True),
    sa.Column('azione', sa.String(length=100), nullable=False),
    sa.Column('campo_modificato', sa.String(length=100), nullable=True),
    sa.Column('valore_precedente', sa.Text(), nullable=True),
    sa.Column('valore_nuovo', sa.Text(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervento_id'], ['interventi.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_storico_asset_id'), 'asset_storico', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_storico_attivo'), 'asset_storico', ['attivo'], unique=False)
    op.create_index(op.f('ix_asset_storico_id'), 'asset_storico', ['id'], unique=False)
    op.create_table('interventi_allegati',
    sa.Column('intervento_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('nome_file', sa.String(length=255), nullable=False),
    sa.Column('nome_originale', sa.String(length=255), nullable=False),
    sa.Column('percorso', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('dimensione', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['intervento_id'], ['interventi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventi_allegati_attivo'), 'interventi_allegati', ['attivo'], unique=False)
    op.create_index(op.f('ix_interventi_allegati_id'), 'interventi_allegati', ['id'], unique=False)
    op.create_index(op.f('ix_interventi_allegati_intervento_id'), 'interventi_allegati', ['intervento_id'], unique=False)
    op.create_table('interventi_sessioni',
    sa.Column('intervento_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ora_inizio', sa.Time(), nullable=True),
    sa.Column('ora_fine', sa.Time(), nullable=True),
    sa.Column('durata_minuti', sa.Integer(), nullable=True),
    sa.Column('tipo_intervento_id', sa.Integer(), nullable=False),
    sa.Column('km_percorsi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tempo_viaggio_minuti', sa.Integer(), nullable=True),
    sa.Column('latitudine_inizio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitudine_inizio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latitudine_fine', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitudine_fine', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['intervento_id'], ['interventi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.ForeignKeyConstraint(['tipo_intervento_id'], ['lookup_tipi_intervento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventi_sessioni_attivo'), 'interventi_sessioni', ['attivo'], unique=False)
    op.create_index(op.f('ix_interventi_sessioni_id'), 'interventi_sessioni', ['id'], unique=False)
    op.create_index(op.f('ix_interventi_sessioni_intervento_id'), 'interventi_sessioni', ['intervento_id'], unique=False)
    op.create_table('interventi_tecnici',
    sa.Column('intervento_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('ruolo', sa.String(length=50), nullable=True),
    sa.Column('ore_lavorate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['intervento_id'], ['interventi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnici.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventi_tecnici_attivo'), 'interventi_tecnici', ['attivo'], unique=False)
    op.create_index(op.f('ix_interventi_tecnici_id'), 'interventi_tecnici', ['id'], unique=False)
    op.create_index(op.f('ix_interventi_tecnici_intervento_id'), 'interventi_tecnici', ['intervento_id'], unique=False)
    op.create_table('interventi_righe',
    sa.Column('intervento_id', sa.Integer(), nullable=False),
    sa.Column('numero_riga', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('quantita', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unita_misura', sa.String(length=20), nullable=True),
    sa.Column('prezzo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sconto_percentuale', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fatturabile', sa.Integer(), nullable=True),
    sa.Column('in_garanzia', sa.Integer(), nullable=True),
    sa.Column('incluso_contratto', sa.Integer(), nullable=True),
    sa.Column('sessione_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['lookup_categorie_attivita.id'], ),
    sa.ForeignKeyConstraint(['intervento_id'], ['interventi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessione_id'], ['interventi_sessioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventi_righe_attivo'), 'interventi_righe', ['attivo'], unique=False)
    op.create_index(op.f('ix_interventi_righe_id'), 'interventi_righe', ['id'], unique=False)
    op.create_index(op.f('ix_interventi_righe_intervento_id'), 'interventi_righe', ['intervento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventi_righe_intervento_id'), table_name='interventi_righe')
    op.drop_index(op.f('ix_interventi_righe_id'), table_name='interventi_righe')
    op.drop_index(op.f('ix_interventi_righe_attivo'), table_name='interventi_righe')
    op.drop_table('interventi_righe')
    op.drop_index(op.f('ix_interventi_tecnici_intervento_id'), table_name='interventi_tecnici')
    op.drop_index(op.f('ix_interventi_tecnici_id'), table_name='interventi_tecnici')
    op.drop_index(op.f('ix_interventi_tecnici_attivo'), table_name='interventi_tecnici')
    op.drop_table('interventi_tecnici')
    op.drop_index(op.f('ix_interventi_sessioni_intervento_id'), table_name='interventi_sessioni')
    op.drop_index(op.f('ix_interventi_sessioni_id'), table_name='interventi_sessioni')
    op.drop_index(op.f('ix_interventi_sessioni_attivo'), table_name='interventi_sessioni')
    op.drop_table('interventi_sessioni')
    op.drop_index(op.f('ix_interventi_allegati_intervento_id'), table_name='interventi_allegati')
    op.drop_index(op.f('ix_interventi_allegati_id'), table_name='interventi_allegati')
    op.drop_index(op.f('ix_interventi_allegati_attivo'), table_name='interventi_allegati')
    op.drop_table('interventi_allegati')
    op.drop_index(op.f('ix_asset_storico_id'), table_name='asset_storico')
    op.drop_index(op.f('ix_asset_storico_attivo'), table_name='asset_storico')
    op.drop_index(op.f('ix_asset_storico_asset_id'), table_name='asset_storico')
    op.drop_table('asset_storico')
    op.drop_index(op.f('ix_ticket_storico_ticket_id'), table_name='ticket_storico')
    op.drop_index(op.f('ix_ticket_storico_id'), table_name='ticket_storico')
    op.drop_index(op.f('ix_ticket_storico_attivo'), table_name='ticket_storico')
    op.drop_table('ticket_storico')
    op.drop_index(op.f('ix_ticket_note_ticket_id'), table_name='ticket_note')
    op.drop_index(op.f('ix_ticket_note_id'), table_name='ticket_note')
    op.drop_index(op.f('ix_ticket_note_attivo'), table_name='ticket_note')
    op.drop_table('ticket_note')
    op.drop_index(op.f('ix_ticket_messaggi_ticket_id'), table_name='ticket_messaggi')
    op.drop_index(op.f('ix_ticket_messaggi_id'), table_name='ticket_messaggi')
    op.drop_index(op.f('ix_ticket_messaggi_attivo'), table_name='ticket_messaggi')
    op.drop_table('ticket_messaggi')
    op.drop_index(op.f('ix_ticket_allegati_ticket_id'), table_name='ticket_allegati')
    op.drop_index(op.f('ix_ticket_allegati_id'), table_name='ticket_allegati')
    op.drop_index(op.f('ix_ticket_allegati_attivo'), table_name='ticket_allegati')
    op.drop_table('ticket_allegati')
    op.drop_index(op.f('ix_richieste_intervento_ticket_id'), table_name='richieste_intervento')
    op.drop_index(op.f('ix_richieste_intervento_stato'), table_name='richieste_intervento')
    op.drop_index(op.f('ix_richieste_intervento_id'), table_name='richieste_intervento')
    op.drop_index(op.f('ix_richieste_intervento_cliente_id'), table_name='richieste_intervento')
    op.drop_index(op.f('ix_richieste_intervento_attivo'), table_name='richieste_intervento')
    op.drop_table('richieste_intervento')
    op.drop_index(op.f('ix_interventi_ticket_id'), table_name='interventi')
    op.drop_index(op.f('ix_interventi_tecnico_id'), table_name='interventi')
    op.drop_index(op.f('ix_interventi_stato_id'), table_name='interventi')
    op.drop_index(op.f('ix_interventi_sincronizzato_gestionale'), table_name='interventi')
    op.drop_index(op.f('ix_interventi_numero'), table_name='interventi')
    op.drop_index(op.f('ix_interventi_id'), table_name='interventi')
    op.drop_index(op.f('ix_interventi_cliente_id'), table_name='interventi')
    op.drop_index(op.f('ix_interventi_attivo'), table_name='interventi')
    op.drop_table('interventi')
    op.drop_index(op.f('ix_asset_credenziali_accessi_id'), table_name='asset_credenziali_accessi')
    op.drop_index(op.f('ix_asset_credenziali_accessi_credenziale_id'), table_name='asset_credenziali_accessi')
    op.drop_index(op.f('ix_asset_credenziali_accessi_attivo'), table_name='asset_credenziali_accessi')
    op.drop_table('asset_credenziali_accessi')
    op.drop_index(op.f('ix_ticket_tecnico_assegnato_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_stato_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_numero'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_cliente_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_attivo'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_kb_articoli_tags_tag_id'), table_name='kb_articoli_tags')
    op.drop_index(op.f('ix_kb_articoli_tags_id'), table_name='kb_articoli_tags')
    op.drop_index(op.f('ix_kb_articoli_tags_attivo'), table_name='kb_articoli_tags')
    op.drop_index(op.f('ix_kb_articoli_tags_articolo_id'), table_name='kb_articoli_tags')
    op.drop_table('kb_articoli_tags')
    op.drop_index(op.f('ix_kb_articoli_feedback_id'), table_name='kb_articoli_feedback')
    op.drop_index(op.f('ix_kb_articoli_feedback_attivo'), table_name='kb_articoli_feedback')
    op.drop_index(op.f('ix_kb_articoli_feedback_articolo_id'), table_name='kb_articoli_feedback')
    op.drop_table('kb_articoli_feedback')
    op.drop_index(op.f('ix_calendario_tecnici_tecnico_id'), table_name='calendario_tecnici')
    op.drop_index(op.f('ix_calendario_tecnici_id'), table_name='calendario_tecnici')
    op.drop_index(op.f('ix_calendario_tecnici_evento_id'), table_name='calendario_tecnici')
    op.drop_index(op.f('ix_calendario_tecnici_attivo'), table_name='calendario_tecnici')
    op.drop_table('calendario_tecnici')
    op.drop_index(op.f('ix_asset_credenziali_id'), table_name='asset_credenziali')
    op.drop_index(op.f('ix_asset_credenziali_attivo'), table_name='asset_credenziali')
    op.drop_index(op.f('ix_asset_credenziali_asset_id'), table_name='asset_credenziali')
    op.drop_table('asset_credenziali')
    op.drop_index(op.f('ix_kb_articoli_titolo'), table_name='kb_articoli')
    op.drop_index(op.f('ix_kb_articoli_slug'), table_name='kb_articoli')
    op.drop_index(op.f('ix_kb_articoli_id'), table_name='kb_articoli')
    op.drop_index(op.f('ix_kb_articoli_categoria_id'), table_name='kb_articoli')
    op.drop_index(op.f('ix_kb_articoli_attivo'), table_name='kb_articoli')
    op.drop_table('kb_articoli')
    op.drop_index(op.f('ix_calendario_sync_log_tecnico_id'), table_name='calendario_sync_log')
    op.drop_index(op.f('ix_calendario_sync_log_id'), table_name='calendario_sync_log')
    op.drop_index(op.f('ix_calendario_sync_log_attivo'), table_name='calendario_sync_log')
    op.drop_table('calendario_sync_log')
    op.drop_index(op.f('ix_calendario_eventi_tecnico_principale_id'), table_name='calendario_eventi')
    op.drop_index(op.f('ix_calendario_eventi_id'), table_name='calendario_eventi')
    op.drop_index(op.f('ix_calendario_eventi_data_inizio'), table_name='calendario_eventi')
    op.drop_index(op.f('ix_calendario_eventi_cliente_id'), table_name='calendario_eventi')
    op.drop_index(op.f('ix_calendario_eventi_attivo'), table_name='calendario_eventi')
    op.drop_table('calendario_eventi')
    op.drop_index(op.f('ix_asset_tipo'), table_name='asset')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_cliente_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_attivo'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_tecnici_username'), table_name='tecnici')
    op.drop_index(op.f('ix_tecnici_id'), table_name='tecnici')
    op.drop_index(op.f('ix_tecnici_email'), table_name='tecnici')
    op.drop_index(op.f('ix_tecnici_attivo'), table_name='tecnici')
    op.drop_table('tecnici')
    op.drop_index(op.f('ix_clienti_portale_id'), table_name='clienti_portale')
    op.drop_index(op.f('ix_clienti_portale_email'), table_name='clienti_portale')
    op.drop_index(op.f('ix_clienti_portale_attivo'), table_name='clienti_portale')
    op.drop_table('clienti_portale')
    op.drop_index(op.f('ix_cache_referenti_id'), table_name='cache_referenti')
    op.drop_index(op.f('ix_cache_referenti_codice_gestionale'), table_name='cache_referenti')
    op.drop_index(op.f('ix_cache_referenti_cliente_id'), table_name='cache_referenti')
    op.drop_index(op.f('ix_cache_referenti_attivo'), table_name='cache_referenti')
    op.drop_table('cache_referenti')
    op.drop_index(op.f('ix_cache_contratti_id'), table_name='cache_contratti')
    op.drop_index(op.f('ix_cache_contratti_codice_gestionale'), table_name='cache_contratti')
    op.drop_index(op.f('ix_cache_contratti_cliente_id'), table_name='cache_contratti')
    op.drop_index(op.f('ix_cache_contratti_attivo'), table_name='cache_contratti')
    op.drop_table('cache_contratti')
    op.drop_index(op.f('ix_sync_log_tipo'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_id'), table_name='sync_log')
    op.drop_index(op.f('ix_sync_log_attivo'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_sla_definizioni_id'), table_name='sla_definizioni')
    op.drop_index(op.f('ix_sla_definizioni_attivo'), table_name='sla_definizioni')
    op.drop_table('sla_definizioni')
    op.drop_index(op.f('ix_lookup_tipi_intervento_id'), table_name='lookup_tipi_intervento')
    op.drop_index(op.f('ix_lookup_tipi_intervento_codice'), table_name='lookup_tipi_intervento')
    op.drop_index(op.f('ix_lookup_tipi_intervento_attivo'), table_name='lookup_tipi_intervento')
    op.drop_table('lookup_tipi_intervento')
    op.drop_index(op.f('ix_lookup_stati_ticket_id'), table_name='lookup_stati_ticket')
    op.drop_index(op.f('ix_lookup_stati_ticket_codice'), table_name='lookup_stati_ticket')
    op.drop_index(op.f('ix_lookup_stati_ticket_attivo'), table_name='lookup_stati_ticket')
    op.drop_table('lookup_stati_ticket')
    op.drop_index(op.f('ix_lookup_stati_intervento_id'), table_name='lookup_stati_intervento')
    op.drop_index(op.f('ix_lookup_stati_intervento_codice'), table_name='lookup_stati_intervento')
    op.drop_index(op.f('ix_lookup_stati_intervento_attivo'), table_name='lookup_stati_intervento')
    op.drop_table('lookup_stati_intervento')
    op.drop_index(op.f('ix_lookup_ruoli_utente_id'), table_name='lookup_ruoli_utente')
    op.drop_index(op.f('ix_lookup_ruoli_utente_codice'), table_name='lookup_ruoli_utente')
    op.drop_index(op.f('ix_lookup_ruoli_utente_attivo'), table_name='lookup_ruoli_utente')
    op.drop_table('lookup_ruoli_utente')
    op.drop_index(op.f('ix_lookup_reparti_id'), table_name='lookup_reparti')
    op.drop_index(op.f('ix_lookup_reparti_codice'), table_name='lookup_reparti')
    op.drop_index(op.f('ix_lookup_reparti_attivo'), table_name='lookup_reparti')
    op.drop_table('lookup_reparti')
    op.drop_index(op.f('ix_lookup_priorita_id'), table_name='lookup_priorita')
    op.drop_index(op.f('ix_lookup_priorita_codice'), table_name='lookup_priorita')
    op.drop_index(op.f('ix_lookup_priorita_attivo'), table_name='lookup_priorita')
    op.drop_table('lookup_priorita')
    op.drop_index(op.f('ix_lookup_origini_intervento_id'), table_name='lookup_origini_intervento')
    op.drop_index(op.f('ix_lookup_origini_intervento_codice'), table_name='lookup_origini_intervento')
    op.drop_index(op.f('ix_lookup_origini_intervento_attivo'), table_name='lookup_origini_intervento')
    op.drop_table('lookup_origini_intervento')
    op.drop_index(op.f('ix_lookup_categorie_attivita_id'), table_name='lookup_categorie_attivita')
    op.drop_index(op.f('ix_lookup_categorie_attivita_codice'), table_name='lookup_categorie_attivita')
    op.drop_index(op.f('ix_lookup_categorie_attivita_attivo'), table_name='lookup_categorie_attivita')
    op.drop_table('lookup_categorie_attivita')
    op.drop_index(op.f('ix_lookup_canali_richiesta_id'), table_name='lookup_canali_richiesta')
    op.drop_index(op.f('ix_lookup_canali_richiesta_codice'), table_name='lookup_canali_richiesta')
    op.drop_index(op.f('ix_lookup_canali_richiesta_attivo'), table_name='lookup_canali_richiesta')
    op.drop_table('lookup_canali_richiesta')
    op.drop_index(op.f('ix_kb_tags_slug'), table_name='kb_tags')
    op.drop_index(op.f('ix_kb_tags_nome'), table_name='kb_tags')
    op.drop_index(op.f('ix_kb_tags_id'), table_name='kb_tags')
    op.drop_index(op.f('ix_kb_tags_attivo'), table_name='kb_tags')
    op.drop_table('kb_tags')
    op.drop_index(op.f('ix_kb_categorie_parent_id'), table_name='kb_categorie')
    op.drop_index(op.f('ix_kb_categorie_id'), table_name='kb_categorie')
    op.drop_index(op.f('ix_kb_categorie_attivo'), table_name='kb_categorie')
    op.drop_table('kb_categorie')
    op.drop_index(op.f('ix_cache_clienti_ragione_sociale'), table_name='cache_clienti')
    op.drop_index(op.f('ix_cache_clienti_id'), table_name='cache_clienti')
    op.drop_index(op.f('ix_cache_clienti_codice_gestionale'), table_name='cache_clienti')
    op.drop_index(op.f('ix_cache_clienti_attivo'), table_name='cache_clienti')
    op.drop_table('cache_clienti')
    # ### end Alembic commands ###
